FROM python:3.11

WORKDIR /app

# Копіюємо requirements.txt в контейнер
COPY requirements.txt .

# Встановлюємо залежності
RUN pip install -r requirements.txt

# Копіюємо всі тести в контейнер
COPY . .

CMD ["pytest"]
